### ISSUE TITLE
Why DeathCore?

### ISSUE THREAD

**Issue by Helias** [NoffearrDeathProjecT/DeathCore#15]
Hello all,

I'm an ex-dev of TrinityCore, I worked with MaNGOS (with UDB) and for TrinityCore, mainly for TrinityCore I made some 3rd-part tools with @ShinDarth like [Keira2](https://github.com/Helias/Keira2), the [TrinityCore API](https://github.com/ShinDarth/TC-JSON-API) and more.

Now, I'm concerning on a new core, [AzerothCore](https://github.com/AzerothCore/), based on SunwellWoW (a project based on an old version of TrinityCore). This core is an innovation for its structure, it is modular, it works with "optional" modules (like [mod-transmog](https://github.com/azerothcore/mod-transmog) or [duel reset](https://github.com/azerothcore/mod-duelreset) ).
If you want read more info about AzerothCore compared with TrinityCore can you read this http://mangosrumors.co.nf/trinitycore-vs-azerothcore/

I'm asking you why don't you join to AzerothCore to join the community and work on a single core?

**Comment by Bodeguero** [comment]
@Helias Well the Azeroth Core platform is with modules and I do not know how to work with modules for that reason I took as a basis the TrinityCore source of version 3.3.5, 4.3.4 and 5.4.8. I've recruited you to help us with this project - of course, if you want to help - I finally know your reputation so I invited you!

I hope you help us - if you do not want to help, I'll understand!

Thank you for accepting the invitation!

**Comment by ShinDarth** [comment]
@Bodeguero modules have been inserted to simplify the work, not to make it harder.

There is no much to know about modules https://github.com/azerothcore/azerothcore-wotlk/wiki/The-Modular-Structure

**Comment by Bodeguero** [comment]
@ShinDarth I will give a verified more make updates I get more add custom scripts not due to work with module or for me to add a custom script will I have to make a correct module?

I will check if I can work with module more in my view as I have already accustomed to the base of TrinityCore without modules - it will be difficult for me to learn - more I will look at the AzerothCore tutorials!

Gratful

**Comment by ShinDarth** [comment]
yes,  modules are meant to add custom features without making the core dirty.. that's why it is better (and easier) to use modules

**Comment by Bodeguero** [comment]
@ShinDarth Nice! It would be like Eluna - you do not need to change anything in Source just add the .lua file in case AzerothCore would add in the module folder
