### ISSUE TITLE
This is a good 434core.

### ISSUE THREAD

**Issue by boom8866** [NoffearrDeathProjecT/DeathCore#16]
I tested DeathCore 434 very good, hope to continue to repair ！

**Comment by Bodeguero** [comment]
@boom8866 Thanks for testing our project at the moment we are recruiting members to the Team! For that reason we are not yet making updates to other sources (4.3.4 and 5.4.8)!

**Comment by cooler-SAI** [comment]
Hey,man! you must add SMART_COMBAT_MOVE for SAI and my scripts)))
https://github.com/cooler-SAI/patch

**Comment by Bodeguero** [comment]
@cooler-SAI I will upgrade your databases to source 4.3.4 - thanks for the support!
