### ISSUE TITLE
Communication Plattform

### ISSUE THREAD

**Issue by Bodeguero** [NoffearrDeathProjecT/DeathCore#2]
For those who want to communicate leave our chat available! Follow the link below:

**[NoffearrDeathProjecT - Chat](https://gitter.im/NoffearrDeathProjecT/DeathCore)**

Gratfull!

**Comment by NightCotRe0110** [comment]
@Bodeguero DeathProject is retur?

**Comment by Bodeguero** [comment]
@NightCotRe0110 yes man 👍
