### ISSUE TITLE
ACE error on compile 5.4.8

### ISSUE THREAD

**Issue by rSafari** [NoffearrDeathProjecT/DeathCore#22]
**Description:**
i got a lot of errors when i trying to compile the 5.4.8 branch.
![untitled](https://cloud.githubusercontent.com/assets/1060150/21502935/bb6a5044-cc68-11e6-98a1-ea886dd940c8.jpg)

heres the full list : https://paste2.org/7nwmOc93

i think all of these errors has related to each other and there is one problem at all.

**Steps to reproduce the problem:**

1. get 5.4.8 branch
2. make cmake
3. try to compile

**Branch(es):** 5.4.8

**DeathCore rev. hash/commit:** Latest

**DCDB version:**  Latest

**Operating system:**  Windows 10

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Bodeguero** [comment]
@rSafari This font is not supported for this version of MS Visual Studio 15, only for MS Visual Studio = 12 (2013).

Requirements

Platform: Windows
CMake
Git Extensions
Boost (x86)
Boost (x64)
MySQL
Microsoft Visual C++ 2008 Redistributable Package (x86)
Microsoft Visual C++ 2008 Redistributable Package (x64)
Microsoft Visual C++ 2010 Redistributable Package (x86)
Microsoft Visual C++ 2010 Redistributable Package (x64)
Microsoft Visual C++ 2012 Redistributable Package (x86)
Microsoft Visual C++ 2012 Redistributable Package (x64)
Microsoft Visual C++ 2013 Redistributable Package (x86)
Microsoft Visual C++ 2013 Redistributable Package (x64)
Microsoft Visual C++ 2015 Redistributable Package (x86)
Microsoft Visual C++ 2015 Redistributable Package (x64)
Microsoft .NET Framework 4.6.2
MS Visual Studio = 12 (2013)(Windows only)
OpenSSL x86
OpenSSL x64
