### ISSUE TITLE
rat

### ISSUE THREAD

**Issue by zamalaev** [NoffearrDeathProjecT/DeathCore#27]
[//]: # (***************************************************************)
[//]: # (** NÃO ELIMINE ESTE MODELO SEU NEGÓCIO SERÁ FECHADO ***********)
[//]: # (***************************************************************)

**Descrição:**
https://github.com/NoffearrDeathProjecT/DeathCore/blob/7.x.x/src/server/scripts/Draenor/Zones/zone_tanaan_jungle.cpp
https://github.com/NoffearrDeathProjecT/DeathCore/blob/7.x.x/src/server/scripts/Pandaria/Zones/zone_isle_of_giants.cpp
and more work content and fixed spell Copyright (C) 2016-2017 DeathCore http://www.noffearrdeathproject.org/ ha-ha-ha rat and noob

stole ProjectLegion)))
**Comportamento atual:** (Conte-nos o que acontece.)

**Comportamento esperado:** (Diga-nos o que deve acontecer em vez disso.)

**Etapas para reproduzir o problema:**

1. 
2. 
3. 

**Branch(es):** 3.3.5 / 4.3.4 / 5.4.8 / 7.x.x

**DeathCore rev. hash/commit:**  

**DCDB versão:**  
PLDB
**Sistema Operacional:**  

[//]: # (Este modelo é para relatórios de problemas. Para outros tipos de relatório, edite-o de acordo.)
[//]: # (Se este for um relatório de falha, inclua o https://gist.github.com/)
[//]: # (Para correções que contêm C ++, crie uma solicitação de solicitação.)

**Comment by Inifield** [comment]
I don't know whether or not something was stolen but what I do know is you're not in position to say such thing zamalaev, you took commit from cmangos and never credited the author.

**Comment by zamalaev** [comment]
https://github.com/OregonCore/OregonCore/commit/5ef4c97d76a43cd5a41e95769d218af6df2fa670
thx ariel

https://github.com/OregonCore/OregonCore/commit/d15203b1d893a1efa43a30a06a6e2d9fda592a88
thx zorix
https://github.com/OregonCore/OregonCore/commit/4c481756e6be69781cb6268787a2df1a9c845de7
thx  Warlockbugs

you blind

**Comment by alexandre433** [comment]
This is not a place to discuss such matter.

**Locked**
