### ISSUE TITLE
Linux support?

### ISSUE THREAD

**Issue by Cubansephiroth** [NoffearrDeathProjecT/DeathCore#28]
Does your core support linux? if not maybe in the near future?

**Comment by EricksOliveira** [comment]
Unfortunately not yet. We have some errors in linux compilation. In the future we will release for linux platform. ;D

**Comment by SkyFire** [comment]
Hard to support Linux when everything is hacked together.

**Comment by Bodeguero** [comment]
@Cubansephiroth What version are you talking about?

**Comment by Cubansephiroth** [comment]
5.4.8

**Comment by Bodeguero** [comment]
@Cubansephiroth 5.4.8 have support for Linux!
