### ISSUE TITLE
Client not authed opcode: 0

### ISSUE THREAD

**Issue by ironhead123** [NoffearrDeathProjecT/DeathCore#30]
Hi,

I use the the newest core 5.4.8.
When i want to log into the server the Worldserver said 

Client not authed opcode: 0
and i cant log in.
When i use another client the server will be seen offline.

I dont know what i do wrong.

**Comment by Bodeguero** [comment]
@ironhead123 Did you verify that ports 8085, 3306 are correct? I will do a test later to see about this error! Thanks for reporting!

**Comment by ironhead123** [comment]
![neue bitmap](https://cloud.githubusercontent.com/assets/6514529/22838059/a072b6c2-efc3-11e6-9fc7-03048267604b.jpg)

smae error and all ports are right

**Comment by Cubansephiroth** [comment]
As of 656bf6ffba5f664d9014878c299c7fc62c3f256b cant reproduce the problem. I can log in without errors.

**Comment by ironhead123** [comment]
hmm,
 thanks for answer. Must be my client. i look for a clean 5.4.8 client.
