### ISSUE TITLE
Will Nefarian ever work?

### ISSUE THREAD

**Issue by brian8544** [NoffearrDeathProjecT/DeathCore#31]
^^^^^^^^

**Comment by Flameshot** [comment]
If they fix gameobject vehicle yes.

**Comment by Bodeguero** [comment]
@brian8544 what branch?

**Comment by brian8544** [comment]
4.3.4

**Comment by Bodeguero** [comment]
@brian8544 The team has not yet done the tests if you want to test and we will be grateful for the reports!
