### ISSUE TITLE
Visual Studio 2013 Support!

### ISSUE THREAD

**Issue by d3athbl0w** [NoffearrDeathProjecT/DeathCore#32]
[//]: # (***************************************************************)
[//]: # (** NÃO ELIMINE ESTE MODELO SEU NEGÓCIO SERÁ FECHADO ***********)
[//]: # (***************************************************************)

**Descrição:**

**Comportamento atual:** (Conte-nos o que acontece.)

**Comportamento esperado:** (Diga-nos o que deve acontecer em vez disso.)

**Etapas para reproduzir o problema:**

1. Support in Visual Studio 2013 have errors in the compilation.

**Branch(es):** 3.3.5 / 7.x.x

**DeathCore rev. hash/commit:**  

Last CORE Rev

**DCDB versão:** 
 
- DCDB 335.62

**Sistema Operacional:**  

- Windows Server 2012 R2

[//]: # (Este modelo é para relatórios de problemas. Para outros tipos de relatório, edite-o de acordo.)
[//]: # (Se este for um relatório de falha, inclua o https://gist.github.com/)
[//]: # (Para correções que contêm C ++, crie uma solicitação de solicitação.)

**Comment by alexandre433** [comment]
Hello,

Please provide us with the errors that the Visual Studio gives.

**Comment by Bodeguero** [comment]
@d3athbl0w version DeathCore 3.3.5 and DeathCore 7.x.x no have support in VS 2013 only VS 2015!

**Comment by Keital** [comment]
@Bodeguero hi friend how are you, im planning giving you a hand soon in your project, i mean if yoou agree.
@d3athbl0w. It wont compile, new TC code standars require specifically vs 2015.

**Comment by d3athbl0w** [comment]
Hi @Bodeguero @Keital @alexandre433  , nice to meet you, thanks for you switf answers, 
I hope soon i can have microsoft visual studio 2015, since windows server 2012r2 is having errors with visual studio 2015 , Thanks for your attention guys.

**Comment by Bodeguero** [comment]
@Keital I invited you again to be a member of the project. If it is possible to update Branch 4.3.4 and Branch 5.4.8 to have support for compiling with VS 2015.

Thanks for the help and support! Welcome back to Team!
