### ISSUE TITLE
Sniffs and PacketParsers...

### ISSUE THREAD

**Issue by Cubansephiroth** [NoffearrDeathProjecT/DeathCore#33]
**Branch(es):**  5.4.8

I found an old repo with lots of sniffs from MoP 5.4.8 (18291,18414) and i was wondering if there is any compatible PacketParser for this core. maybe i can get something useful from there.

**Comment by Bodeguero** [comment]
@Cubansephiroth We need to do the tests to see if it's compatible - you can do it yourself~!
