### ISSUE TITLE
Unknown column 'vipTime'

### ISSUE THREAD

**Issue by Reckfull** [NoffearrDeathProjecT/DeathCore#38]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**I Compiling the source but when start my worldserver this close to finish for any reason:**

**Start de ./worldserver process and stop after finish:**

**Worked fine**

**Steps to reproduce the problem:**

1. Tap ./worldserver
2. Loading...
3.  Segmentation fault.

**Branch(es):** 3.3.5

**>DeathCore rev. 3.3.5a 20-02-2017 08:35:00 +3.3.5a **  

**DCDB_full_335.62_2016_10_29:**  

**Unix (Debian Jessie 8.7:**  

Logs:

Server.log --
DeathCore rev. 3.3.5a 20-02-2017 08:35:00 +3.3.5a (Arquivado branch) (Unix, Release, Static) (worldserver-daemon) ready...
Creating a list of usable transmogrification entries...
Deleting non-existing transmogrification entries...
Deleting non-existing transmogrification entries...

DBError.log --
[1054] Unknown column 'vipTime' in 'where clause'
Your database structure is not up to date. Please make sure you've executed all queries in the sql/updates folders.

-----------------------
I applied all updates and SQLs in database. Compiling without errors.

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by alexandre433** [comment]
Hello,

Did you try to re-apply all of the SQL's? Deleting the databases and then re-applying the SQL's?

**Comment by Reckfull** [comment]
Hi dear.
Re-compile everything and it didn't work, I do not know what happened.
