### ISSUE TITLE
Custom script (npc_promotion.cpp) not work

### ISSUE THREAD

**Issue by Reckfull** [NoffearrDeathProjecT/DeathCore#39]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** The custom "script npc_promotion.cpp" not working properly

**Current behaviour:** 

-- When using npc at level 1 does not give you the promotion, only if you are level 2. Then, you raise level and gives you the mount that brings by default the script but not the other objects you add. It shows the following message: "You do not have any space in your bags" But I have bags with spaces, even those of 36 slots.

**Expected behaviour:** 

-- That the npc you of the promotion of level and objects correctly to the level 1, with all the included objects if you have space in your bags.

**Steps to reproduce the problem:**

Go to the npc.
Speak with he.
This no make anything.
Level Up 1 to 2.
Speak next with he.
Select a promo (in my case Holy Paladin for test the items).
Work fine with level and the first item (the mount // 49284).
And the last message show you is "You do not have any space in your bags" So have slots in your bags available.

**Branch(es): 3.3.5a**

**DeathCore rev. 3.3.5a 20-02-2017 08:35:00 +3.3.5a:**  

**DCDB version:  DCDB_full_335.62_2016_10_29**

**Operating system: Linux Debian 8.7**  

Here are the test lines I added in the script with the items ID.
----------------------------------------------------------------------------------------

								  case GOSSIP_ACTION_INFO_DEF+40: // Paladin Holy
								  player->AddItem(49284, 1); // The mount of you added
								  player->AddItem(42725, 1);
								  player->AddItem(42728, 1);
								  player->AddItem(42726, 1);
								  player->AddItem(42730, 1);
								  player->AddItem(42727, 1);
								  player->AddItem(42724, 1);
								  player->AddItem(42729, 1);
								  player->AddItem(42723, 1);
								  player->AddItem(40705, 1);
								  player->AddItem(37216, 1);
								  player->AddItem(37681, 1);
								  player->AddItem(37657, 1);
								  player->AddItem(37844, 1);								  
								  CloseGossipMenuFor(player);
								  break;

**Comment by Bodeguero** [comment]
@Reckfull Could you tell me the Bag ID (which you added to be used)? Another question this Bag did you add it to initially start in place of the Standard Bag? Because from what I understand you added many items in the promotion and the initial bag does not have the slots needed to receive the item.

PS: Forgive me for the mistakes in English - I'm so bad at speaking in that language.

Gratfull.

**Comment by alexandre433** [comment]
Fixed

**Comment by Reckfull** [comment]
@Bodeguero No problem.
I used a few bags for test and see what is the problem, after that I reduced the number of items per promotion to see if the initial bag took them and did not work either.

Thanks for the proyect dude!
