### ISSUE TITLE
Repo Setup, hash revision not works!!!!!

### ISSUE THREAD

**Issue by Bodeguero** [NoffearrDeathProjecT/DeathCore#4]
**Description:** Repo Setup, hash revision not works!!!!!

**Steps to reproduce the problem:**

1.  Could not find a proper repository signature (hash) - you may need to pull tags with git fetch -t
Continuing anyway - note that the versionstring will be set to "unknown 1970-01-01 00:00:00 (Archived)"

**Branch(es):** 5.4.8 / 4.3.4 / 3.3.5

**DeathCore rev. hash/commit:**  5.4.8 https://github.com/NoffearrDeathProjecT/DeathCore/commit/229d90c5585c3307ff91cacaf56d6f2be9a5b824 / 4.3.4 https://github.com/NoffearrDeathProjecT/DeathCore/commit/974045c77ba00e29466da6f7859550242f49be6f / 3.3.5 https://github.com/NoffearrDeathProjecT/DeathCore/commit/b3af2efcfc6fdcdff3cd13e0331685e4f488d083

**DC-DB version:** DCDB 548.01 / DCDB 434.13 / DCDB 335.62

**Operating system:**  Windows 10 Pro

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Keital** [comment]
Hash already added in 5.4.8 branch test it

**Comment by Bodeguero** [comment]
@Keital Thanks for u support
