### ISSUE TITLE
unstable

### ISSUE THREAD

**Issue by andryus** [NoffearrDeathProjecT/DeathCore#5]
CRASH EVERY HOUR.

﻿[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**

**Current behaviour:** (Tell us what happens.)

**Expected behaviour:** (Tell us what should happen instead.)

**Steps to reproduce the problem:**

1. 
2. 
3. 

**Branch(es):** 5.4.8 / 4.3.4 / 3.3.5

**DeathCore rev. hash/commit:**  

**DC-DB version:**  

**Operating system:**  

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Keital** [comment]
Issue template exist for a reason, "CRASH EVERY HOUR." is not an issue, is a comment, provide useful descriptions of issues
