### ISSUE TITLE
Help me please, damage, hp of creatures

### ISSUE THREAD

**Issue by andryus** [NoffearrDeathProjecT/DeathCore#6]
## **4.3.4 Cataclysm**

I currently have a problem with life and damage to creatures

http://i.imgur.com/nIUqQ1y.jpg

http://i.imgur.com/oYmLtp0.jpg

http://i.imgur.com/Li9iTVn.jpg

I tried several configurations and the problem persists

Rate.Creature.Normal.Damage          = 1 
Rate.Creature.Elite.Elite.Damage     = 0.2 **I have placed 1**
Rate.Creature.Elite.RARE.Damage      = 0.2 **I have placed 1**
Rate.Creature.Elite.RAREELITE.Damage = 0.2 **I have placed 1**
Rate.Creature.Elite.WORLDBOSS.Damage = 0.2 **I have placed 1**

I wish you could help me

**Comment by Bodeguero** [comment]
@andryus What raid or is it a dungeon? Could you be more specific on the subject? Next time open the Issue correctly, otherwise I'll delete it!

**Comment by andryus** [comment]
@Bodeguero  Sorry. The problem is in all creatures dungeon's

**Comment by Bodeguero** [comment]
@andryus I'll be checking this out - but first we're focused on the main things like Initial Quests, Races, and Classes. Then we will work with Dungeons, Raids and Battleground!

Gratful!

**Comment by andryus** [comment]
I fix that, Using the following statistics::

Rate.Creature.Normal.Damage          = 1
Rate.Creature.Elite.Elite.Damage     = 0.4
Rate.Creature.Elite.RARE.Damage      = 0.2
Rate.Creature.Elite.RAREELITE.Damage = 0.2
Rate.Creature.Elite.WORLDBOSS.Damage = 0.2

Rate.Creature.Normal.SpellDamage          = 1
Rate.Creature.Elite.Elite.SpellDamage     = 0.1
Rate.Creature.Elite.RARE.SpellDamage      = 0.1
Rate.Creature.Elite.RAREELITE.SpellDamage = 0.1
Rate.Creature.Elite.WORLDBOSS.SpellDamage = 0.1

Rate.Creature.Normal.HP          = 1
Rate.Creature.Elite.Elite.HP     = 0.2
Rate.Creature.Elite.RARE.HP      = 0.2
Rate.Creature.Elite.RAREELITE.HP = 0.2
Rate.Creature.Elite.WORLDBOSS.HP = 0.2

## **If someone has the same problem you can try this**

**Comment by Bodeguero** [comment]
@andryus You are testing the damage without items is logical that the damages will be high Look test the damages with Equipments and not without item! 🤐 

Gratful!

**Comment by Bodeguero** [comment]
Fixed bug - I'll be sending the new database!

![wowscrnshot_111316_175032](https://cloud.githubusercontent.com/assets/8006687/20248799/5526a5e6-a9ca-11e6-9613-db096356f5ee.jpg)

![wowscrnshot_111316_175146](https://cloud.githubusercontent.com/assets/8006687/20248800/552befd8-a9ca-11e6-973d-9341ea4e4761.jpg)

![wowscrnshot_111316_175150](https://cloud.githubusercontent.com/assets/8006687/20248801/553512b6-a9ca-11e6-8940-14bab9577aa1.jpg)
